// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need the session-mode pooler (or a direct connection), not
    // the transaction-mode pooler used by the app at runtime.
    url: process.env["DIRECT_URL"],
  },
});
